# Generated by Django 3.0.3 on 2020-03-01 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anamnese', models.CharField(help_text='Anamnese', max_length=100)),
                ('dobras', models.CharField(help_text='Dobras', max_length=100)),
                ('ergometrico', models.CharField(help_text='Ergométrico', max_length=100)),
                ('data_avaliacao', models.DateField()),
                ('data_notifica', models.DateField()),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aluno.Aluno')),
            ],
        ),
    ]
