# Generated by Django 3.0.3 on 2020-03-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='data_avaliacao',
        ),
    ]
