# Generated by Django 3.0.3 on 2020-03-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_remove_avaliacao_data_avaliacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='data_notifica',
            new_name='data_avaliacao',
        ),
    ]
