# Generated by Django 3.0.3 on 2020-03-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0003_auto_20200301_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='data_notifica',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='data_avaliacao',
            field=models.DateField(null=True),
        ),
    ]
