# Generated by Django 3.0.3 on 2020-03-03 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0002_ferias_altera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferias',
            name='altera',
        ),
    ]
