# Generated by Django 3.0.3 on 2020-03-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='data_baixa',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='vencimento',
            field=models.DateField(null=True),
        ),
    ]
