# Generated by Django 3.0.3 on 2020-03-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0003_pagamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data_baixa',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
