# Generated by Django 3.0.3 on 2020-03-01 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('identidade', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=25)),
                ('cidade', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=15)),
                ('plano', models.CharField(max_length=10)),
                ('acesso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
