# Generated by Django 3.0.3 on 2020-03-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_auto_20200301_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='plano',
            field=models.CharField(choices=[('1', 'Plano mensal'), ('2', 'Plano anual')], max_length=1),
        ),
    ]
