# Generated by Django 3.0.3 on 2020-03-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_auto_20200301_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='plano',
        ),
    ]
