# Generated by Django 3.0.3 on 2020-03-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_remove_aluno_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='plano',
            field=models.CharField(choices=[('1', 'Plano mensal'), ('2', 'Plano anual')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
