# Generated by Django 3.0.3 on 2020-03-11 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aluno', '0007_auto_20200311_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='acesso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
