# Generated by Django 3.0.3 on 2020-03-11 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0008_auto_20200311_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='acesso',
        ),
    ]
