# Generated by Django 3.0.3 on 2020-03-29 14:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0009_remove_aluno_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.CharField(max_length=70),
            preserve_default=False,
        ),
    ]
