# Generated by Django 3.0.3 on 2020-03-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0010_aluno_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
    ]
