# Generated by Django 3.0.3 on 2020-03-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0011_remove_aluno_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
